window.JEALIN_DEFAULT_CONFIG = {
  "settings": {
    "brand": "Jealin",
    "tagline": "Priceless beauty",
    "location": "Lagos, Nigeria",
    "whatsappNumber": "",
    "heroImage": "assets/jealin-hero-jewelry.png"
  },
  "categories": [
    {
      "key": "necklace",
      "cn": "项链",
      "en": "Necklaces"
    },
    {
      "key": "bracelet",
      "cn": "手链",
      "en": "Bracelets"
    },
    {
      "key": "ring",
      "cn": "戒指",
      "en": "Rings"
    },
    {
      "key": "earrings",
      "cn": "耳钉",
      "en": "Earrings"
    }
  ],
  "products": [
    {
      "id": "jealin-earrings-001",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-001.jpg",
      "cn": "轻奢耳钉 001",
      "en": "Luxe Earrings 001",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-necklace-002",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-002.jpg",
      "cn": "轻奢项链 002",
      "en": "Luxe Necklace 002",
      "metaCn": "锁骨线条 / 日常叠戴",
      "metaEn": "Collarbone accent / Everyday layering",
      "price": 38888,
      "descCn": "适合通勤、约会和聚会佩戴，细链或吊坠设计能自然提亮颈部线条。",
      "descEn": "Designed for workdays, dates and gatherings, with a refined chain or pendant that brightens the neckline."
    },
    {
      "id": "jealin-earrings-003",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-003.jpg",
      "cn": "轻奢耳钉 003",
      "en": "Luxe Earrings 003",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-004",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-004.jpg",
      "cn": "轻奢耳钉 004",
      "en": "Luxe Earrings 004",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-ring-005",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-005.jpg",
      "cn": "轻奢戒指 005",
      "en": "Luxe Ring 005",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-006",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-006.jpg",
      "cn": "轻奢戒指 006",
      "en": "Luxe Ring 006",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-007",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-007.jpg",
      "cn": "轻奢戒指 007",
      "en": "Luxe Ring 007",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-008",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-008.jpg",
      "cn": "轻奢戒指 008",
      "en": "Luxe Ring 008",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-009",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-009.jpg",
      "cn": "轻奢戒指 009",
      "en": "Luxe Ring 009",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-010",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-010.jpg",
      "cn": "轻奢戒指 010",
      "en": "Luxe Ring 010",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-011",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-011.jpg",
      "cn": "轻奢戒指 011",
      "en": "Luxe Ring 011",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-012",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-012.jpg",
      "cn": "轻奢戒指 012",
      "en": "Luxe Ring 012",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-013",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-013.jpg",
      "cn": "轻奢戒指 013",
      "en": "Luxe Ring 013",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-014",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-014.jpg",
      "cn": "轻奢戒指 014",
      "en": "Luxe Ring 014",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-bracelet-015",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-015.jpg",
      "cn": "精致手链 015",
      "en": "Refined Bracelet 015",
      "metaCn": "腕间点缀 / 轻盈闪耀",
      "metaEn": "Wrist accent / Light-catching shine",
      "price": 38888,
      "descCn": "适合单戴或叠戴，水钻、珍珠或金属链条让手腕更显精致。",
      "descEn": "Made for solo styling or stacking, adding a polished sparkle to the wrist with stones, pearls or metal links."
    },
    {
      "id": "jealin-bracelet-016",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-016.jpg",
      "cn": "精致手链 016",
      "en": "Refined Bracelet 016",
      "metaCn": "腕间点缀 / 轻盈闪耀",
      "metaEn": "Wrist accent / Light-catching shine",
      "price": 38888,
      "descCn": "适合单戴或叠戴，水钻、珍珠或金属链条让手腕更显精致。",
      "descEn": "Made for solo styling or stacking, adding a polished sparkle to the wrist with stones, pearls or metal links."
    },
    {
      "id": "jealin-necklace-017",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-017.jpg",
      "cn": "轻奢项链 017",
      "en": "Luxe Necklace 017",
      "metaCn": "锁骨线条 / 日常叠戴",
      "metaEn": "Collarbone accent / Everyday layering",
      "price": 38888,
      "descCn": "适合通勤、约会和聚会佩戴，细链或吊坠设计能自然提亮颈部线条。",
      "descEn": "Designed for workdays, dates and gatherings, with a refined chain or pendant that brightens the neckline."
    },
    {
      "id": "jealin-necklace-018",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-018.jpg",
      "cn": "轻奢项链 018",
      "en": "Luxe Necklace 018",
      "metaCn": "锁骨线条 / 日常叠戴",
      "metaEn": "Collarbone accent / Everyday layering",
      "price": 38888,
      "descCn": "适合通勤、约会和聚会佩戴，细链或吊坠设计能自然提亮颈部线条。",
      "descEn": "Designed for workdays, dates and gatherings, with a refined chain or pendant that brightens the neckline."
    },
    {
      "id": "jealin-necklace-019",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-019.jpg",
      "cn": "轻奢项链 019",
      "en": "Luxe Necklace 019",
      "metaCn": "锁骨线条 / 日常叠戴",
      "metaEn": "Collarbone accent / Everyday layering",
      "price": 38888,
      "descCn": "适合通勤、约会和聚会佩戴，细链或吊坠设计能自然提亮颈部线条。",
      "descEn": "Designed for workdays, dates and gatherings, with a refined chain or pendant that brightens the neckline."
    },
    {
      "id": "jealin-necklace-020",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-020.jpg",
      "cn": "轻奢项链 020",
      "en": "Luxe Necklace 020",
      "metaCn": "锁骨线条 / 日常叠戴",
      "metaEn": "Collarbone accent / Everyday layering",
      "price": 38888,
      "descCn": "适合通勤、约会和聚会佩戴，细链或吊坠设计能自然提亮颈部线条。",
      "descEn": "Designed for workdays, dates and gatherings, with a refined chain or pendant that brightens the neckline."
    },
    {
      "id": "jealin-earrings-021",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-021.jpg",
      "cn": "轻奢耳钉 021",
      "en": "Luxe Earrings 021",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-ring-022",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-022.jpg",
      "cn": "轻奢戒指 022",
      "en": "Luxe Ring 022",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-necklace-023",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-023.jpg",
      "cn": "轻奢项链 023",
      "en": "Luxe Necklace 023",
      "metaCn": "锁骨线条 / 日常叠戴",
      "metaEn": "Collarbone accent / Everyday layering",
      "price": 38888,
      "descCn": "适合通勤、约会和聚会佩戴，细链或吊坠设计能自然提亮颈部线条。",
      "descEn": "Designed for workdays, dates and gatherings, with a refined chain or pendant that brightens the neckline."
    },
    {
      "id": "jealin-necklace-024",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-024.jpg",
      "cn": "轻奢项链 024",
      "en": "Luxe Necklace 024",
      "metaCn": "锁骨线条 / 日常叠戴",
      "metaEn": "Collarbone accent / Everyday layering",
      "price": 38888,
      "descCn": "适合通勤、约会和聚会佩戴，细链或吊坠设计能自然提亮颈部线条。",
      "descEn": "Designed for workdays, dates and gatherings, with a refined chain or pendant that brightens the neckline."
    },
    {
      "id": "jealin-necklace-025",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-025.jpg",
      "cn": "轻奢项链 025",
      "en": "Luxe Necklace 025",
      "metaCn": "锁骨线条 / 日常叠戴",
      "metaEn": "Collarbone accent / Everyday layering",
      "price": 38888,
      "descCn": "适合通勤、约会和聚会佩戴，细链或吊坠设计能自然提亮颈部线条。",
      "descEn": "Designed for workdays, dates and gatherings, with a refined chain or pendant that brightens the neckline."
    },
    {
      "id": "jealin-necklace-026",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-026.jpg",
      "cn": "轻奢项链 026",
      "en": "Luxe Necklace 026",
      "metaCn": "锁骨线条 / 日常叠戴",
      "metaEn": "Collarbone accent / Everyday layering",
      "price": 38888,
      "descCn": "适合通勤、约会和聚会佩戴，细链或吊坠设计能自然提亮颈部线条。",
      "descEn": "Designed for workdays, dates and gatherings, with a refined chain or pendant that brightens the neckline."
    },
    {
      "id": "jealin-necklace-027",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-027.jpg",
      "cn": "轻奢项链 027",
      "en": "Luxe Necklace 027",
      "metaCn": "锁骨线条 / 日常叠戴",
      "metaEn": "Collarbone accent / Everyday layering",
      "price": 38888,
      "descCn": "适合通勤、约会和聚会佩戴，细链或吊坠设计能自然提亮颈部线条。",
      "descEn": "Designed for workdays, dates and gatherings, with a refined chain or pendant that brightens the neckline."
    },
    {
      "id": "jealin-necklace-028",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-028.jpg",
      "cn": "轻奢项链 028",
      "en": "Luxe Necklace 028",
      "metaCn": "锁骨线条 / 日常叠戴",
      "metaEn": "Collarbone accent / Everyday layering",
      "price": 38888,
      "descCn": "适合通勤、约会和聚会佩戴，细链或吊坠设计能自然提亮颈部线条。",
      "descEn": "Designed for workdays, dates and gatherings, with a refined chain or pendant that brightens the neckline."
    },
    {
      "id": "jealin-necklace-029",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-029.jpg",
      "cn": "轻奢项链 029",
      "en": "Luxe Necklace 029",
      "metaCn": "锁骨线条 / 日常叠戴",
      "metaEn": "Collarbone accent / Everyday layering",
      "price": 38888,
      "descCn": "适合通勤、约会和聚会佩戴，细链或吊坠设计能自然提亮颈部线条。",
      "descEn": "Designed for workdays, dates and gatherings, with a refined chain or pendant that brightens the neckline."
    },
    {
      "id": "jealin-earrings-030",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-030.jpg",
      "cn": "轻奢耳钉 030",
      "en": "Luxe Earrings 030",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-031",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-031.jpg",
      "cn": "轻奢耳钉 031",
      "en": "Luxe Earrings 031",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-032",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-032.jpg",
      "cn": "轻奢耳钉 032",
      "en": "Luxe Earrings 032",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-033",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-033.jpg",
      "cn": "轻奢耳钉 033",
      "en": "Luxe Earrings 033",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-034",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-034.jpg",
      "cn": "轻奢耳钉 034",
      "en": "Luxe Earrings 034",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-035",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-035.jpg",
      "cn": "轻奢耳钉 035",
      "en": "Luxe Earrings 035",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-036",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-036.jpg",
      "cn": "轻奢耳钉 036",
      "en": "Luxe Earrings 036",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-037",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-037.jpg",
      "cn": "轻奢耳钉 037",
      "en": "Luxe Earrings 037",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-038",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-038.jpg",
      "cn": "轻奢耳钉 038",
      "en": "Luxe Earrings 038",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-039",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-039.jpg",
      "cn": "轻奢耳钉 039",
      "en": "Luxe Earrings 039",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-040",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-040.jpg",
      "cn": "轻奢耳钉 040",
      "en": "Luxe Earrings 040",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-041",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-041.jpg",
      "cn": "轻奢耳钉 041",
      "en": "Luxe Earrings 041",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-042",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-042.jpg",
      "cn": "轻奢耳钉 042",
      "en": "Luxe Earrings 042",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-043",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-043.jpg",
      "cn": "轻奢耳钉 043",
      "en": "Luxe Earrings 043",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-044",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-044.jpg",
      "cn": "轻奢耳钉 044",
      "en": "Luxe Earrings 044",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-045",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-045.jpg",
      "cn": "轻奢耳钉 045",
      "en": "Luxe Earrings 045",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-046",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-046.jpg",
      "cn": "轻奢耳钉 046",
      "en": "Luxe Earrings 046",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-047",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-047.jpg",
      "cn": "轻奢耳钉 047",
      "en": "Luxe Earrings 047",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-048",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-048.jpg",
      "cn": "轻奢耳钉 048",
      "en": "Luxe Earrings 048",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-049",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-049.jpg",
      "cn": "轻奢耳钉 049",
      "en": "Luxe Earrings 049",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-050",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-050.jpg",
      "cn": "轻奢耳钉 050",
      "en": "Luxe Earrings 050",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-051",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-051.jpg",
      "cn": "轻奢耳钉 051",
      "en": "Luxe Earrings 051",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-necklace-052",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-052.jpg",
      "cn": "轻奢项链 052",
      "en": "Luxe Necklace 052",
      "metaCn": "锁骨线条 / 日常叠戴",
      "metaEn": "Collarbone accent / Everyday layering",
      "price": 38888,
      "descCn": "适合通勤、约会和聚会佩戴，细链或吊坠设计能自然提亮颈部线条。",
      "descEn": "Designed for workdays, dates and gatherings, with a refined chain or pendant that brightens the neckline."
    },
    {
      "id": "jealin-ring-053",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-053.jpg",
      "cn": "轻奢戒指 053",
      "en": "Luxe Ring 053",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-054",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-054.jpg",
      "cn": "轻奢戒指 054",
      "en": "Luxe Ring 054",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-055",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-055.jpg",
      "cn": "轻奢戒指 055",
      "en": "Luxe Ring 055",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-056",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-056.jpg",
      "cn": "轻奢戒指 056",
      "en": "Luxe Ring 056",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-057",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-057.jpg",
      "cn": "轻奢戒指 057",
      "en": "Luxe Ring 057",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-058",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-058.jpg",
      "cn": "轻奢戒指 058",
      "en": "Luxe Ring 058",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-059",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-059.jpg",
      "cn": "轻奢戒指 059",
      "en": "Luxe Ring 059",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-060",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-060.jpg",
      "cn": "轻奢戒指 060",
      "en": "Luxe Ring 060",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-061",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-061.jpg",
      "cn": "轻奢戒指 061",
      "en": "Luxe Ring 061",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-062",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-062.jpg",
      "cn": "轻奢戒指 062",
      "en": "Luxe Ring 062",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-063",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-063.jpg",
      "cn": "轻奢戒指 063",
      "en": "Luxe Ring 063",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-064",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-064.jpg",
      "cn": "轻奢戒指 064",
      "en": "Luxe Ring 064",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-065",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-065.jpg",
      "cn": "轻奢戒指 065",
      "en": "Luxe Ring 065",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-066",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-066.jpg",
      "cn": "轻奢戒指 066",
      "en": "Luxe Ring 066",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-067",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-067.jpg",
      "cn": "轻奢戒指 067",
      "en": "Luxe Ring 067",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-068",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-068.jpg",
      "cn": "轻奢戒指 068",
      "en": "Luxe Ring 068",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-069",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-069.jpg",
      "cn": "轻奢戒指 069",
      "en": "Luxe Ring 069",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-070",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-070.jpg",
      "cn": "轻奢戒指 070",
      "en": "Luxe Ring 070",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-071",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-071.jpg",
      "cn": "轻奢戒指 071",
      "en": "Luxe Ring 071",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-072",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-072.jpg",
      "cn": "轻奢戒指 072",
      "en": "Luxe Ring 072",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-073",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-073.jpg",
      "cn": "轻奢戒指 073",
      "en": "Luxe Ring 073",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-074",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-074.jpg",
      "cn": "轻奢戒指 074",
      "en": "Luxe Ring 074",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-075",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-075.jpg",
      "cn": "轻奢戒指 075",
      "en": "Luxe Ring 075",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-076",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-076.jpg",
      "cn": "轻奢戒指 076",
      "en": "Luxe Ring 076",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-077",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-077.jpg",
      "cn": "轻奢戒指 077",
      "en": "Luxe Ring 077",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-earrings-078",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-078.jpg",
      "cn": "轻奢耳钉 078",
      "en": "Luxe Earrings 078",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-bracelet-079",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-079.jpg",
      "cn": "精致手链 079",
      "en": "Refined Bracelet 079",
      "metaCn": "腕间点缀 / 轻盈闪耀",
      "metaEn": "Wrist accent / Light-catching shine",
      "price": 38888,
      "descCn": "适合单戴或叠戴，水钻、珍珠或金属链条让手腕更显精致。",
      "descEn": "Made for solo styling or stacking, adding a polished sparkle to the wrist with stones, pearls or metal links."
    },
    {
      "id": "jealin-bracelet-080",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-080.jpg",
      "cn": "精致手链 080",
      "en": "Refined Bracelet 080",
      "metaCn": "腕间点缀 / 轻盈闪耀",
      "metaEn": "Wrist accent / Light-catching shine",
      "price": 38888,
      "descCn": "适合单戴或叠戴，水钻、珍珠或金属链条让手腕更显精致。",
      "descEn": "Made for solo styling or stacking, adding a polished sparkle to the wrist with stones, pearls or metal links."
    },
    {
      "id": "jealin-ring-081",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-081.jpg",
      "cn": "轻奢戒指 081",
      "en": "Luxe Ring 081",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-082",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-082.jpg",
      "cn": "轻奢戒指 082",
      "en": "Luxe Ring 082",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-083",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-083.jpg",
      "cn": "轻奢戒指 083",
      "en": "Luxe Ring 083",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-084",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-084.jpg",
      "cn": "轻奢戒指 084",
      "en": "Luxe Ring 084",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-085",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-085.jpg",
      "cn": "轻奢戒指 085",
      "en": "Luxe Ring 085",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-ring-086",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-086.jpg",
      "cn": "轻奢戒指 086",
      "en": "Luxe Ring 086",
      "metaCn": "指间亮点 / 优雅造型",
      "metaEn": "Finger accent / Elegant styling",
      "price": 38888,
      "descCn": "适合作为日常造型亮点，也适合礼物场景，细节精致但不夸张。",
      "descEn": "A refined accent for daily outfits or gifting, detailed enough to stand out without feeling heavy."
    },
    {
      "id": "jealin-bracelet-087",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-087.jpg",
      "cn": "精致手链 087",
      "en": "Refined Bracelet 087",
      "metaCn": "腕间点缀 / 轻盈闪耀",
      "metaEn": "Wrist accent / Light-catching shine",
      "price": 38888,
      "descCn": "适合单戴或叠戴，水钻、珍珠或金属链条让手腕更显精致。",
      "descEn": "Made for solo styling or stacking, adding a polished sparkle to the wrist with stones, pearls or metal links."
    },
    {
      "id": "jealin-bracelet-088",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-088.jpg",
      "cn": "精致手链 088",
      "en": "Refined Bracelet 088",
      "metaCn": "腕间点缀 / 轻盈闪耀",
      "metaEn": "Wrist accent / Light-catching shine",
      "price": 38888,
      "descCn": "适合单戴或叠戴，水钻、珍珠或金属链条让手腕更显精致。",
      "descEn": "Made for solo styling or stacking, adding a polished sparkle to the wrist with stones, pearls or metal links."
    },
    {
      "id": "jealin-necklace-089",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-089.jpg",
      "cn": "轻奢项链 089",
      "en": "Luxe Necklace 089",
      "metaCn": "锁骨线条 / 日常叠戴",
      "metaEn": "Collarbone accent / Everyday layering",
      "price": 38888,
      "descCn": "适合通勤、约会和聚会佩戴，细链或吊坠设计能自然提亮颈部线条。",
      "descEn": "Designed for workdays, dates and gatherings, with a refined chain or pendant that brightens the neckline."
    },
    {
      "id": "jealin-bracelet-090",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-090.jpg",
      "cn": "精致手链 090",
      "en": "Refined Bracelet 090",
      "metaCn": "腕间点缀 / 轻盈闪耀",
      "metaEn": "Wrist accent / Light-catching shine",
      "price": 38888,
      "descCn": "适合单戴或叠戴，水钻、珍珠或金属链条让手腕更显精致。",
      "descEn": "Made for solo styling or stacking, adding a polished sparkle to the wrist with stones, pearls or metal links."
    },
    {
      "id": "jealin-bracelet-091",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-091.jpg",
      "cn": "精致手链 091",
      "en": "Refined Bracelet 091",
      "metaCn": "腕间点缀 / 轻盈闪耀",
      "metaEn": "Wrist accent / Light-catching shine",
      "price": 38888,
      "descCn": "适合单戴或叠戴，水钻、珍珠或金属链条让手腕更显精致。",
      "descEn": "Made for solo styling or stacking, adding a polished sparkle to the wrist with stones, pearls or metal links."
    },
    {
      "id": "jealin-bracelet-092",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-092.jpg",
      "cn": "精致手链 092",
      "en": "Refined Bracelet 092",
      "metaCn": "腕间点缀 / 轻盈闪耀",
      "metaEn": "Wrist accent / Light-catching shine",
      "price": 38888,
      "descCn": "适合单戴或叠戴，水钻、珍珠或金属链条让手腕更显精致。",
      "descEn": "Made for solo styling or stacking, adding a polished sparkle to the wrist with stones, pearls or metal links."
    },
    {
      "id": "jealin-bracelet-093",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-093.jpg",
      "cn": "精致手链 093",
      "en": "Refined Bracelet 093",
      "metaCn": "腕间点缀 / 轻盈闪耀",
      "metaEn": "Wrist accent / Light-catching shine",
      "price": 38888,
      "descCn": "适合单戴或叠戴，水钻、珍珠或金属链条让手腕更显精致。",
      "descEn": "Made for solo styling or stacking, adding a polished sparkle to the wrist with stones, pearls or metal links."
    },
    {
      "id": "jealin-bracelet-094",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-094.jpg",
      "cn": "精致手链 094",
      "en": "Refined Bracelet 094",
      "metaCn": "腕间点缀 / 轻盈闪耀",
      "metaEn": "Wrist accent / Light-catching shine",
      "price": 38888,
      "descCn": "适合单戴或叠戴，水钻、珍珠或金属链条让手腕更显精致。",
      "descEn": "Made for solo styling or stacking, adding a polished sparkle to the wrist with stones, pearls or metal links."
    },
    {
      "id": "jealin-necklace-095",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-095.jpg",
      "cn": "轻奢项链 095",
      "en": "Luxe Necklace 095",
      "metaCn": "锁骨线条 / 日常叠戴",
      "metaEn": "Collarbone accent / Everyday layering",
      "price": 38888,
      "descCn": "适合通勤、约会和聚会佩戴，细链或吊坠设计能自然提亮颈部线条。",
      "descEn": "Designed for workdays, dates and gatherings, with a refined chain or pendant that brightens the neckline."
    },
    {
      "id": "jealin-bracelet-096",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-096.jpg",
      "cn": "精致手链 096",
      "en": "Refined Bracelet 096",
      "metaCn": "腕间点缀 / 轻盈闪耀",
      "metaEn": "Wrist accent / Light-catching shine",
      "price": 38888,
      "descCn": "适合单戴或叠戴，水钻、珍珠或金属链条让手腕更显精致。",
      "descEn": "Made for solo styling or stacking, adding a polished sparkle to the wrist with stones, pearls or metal links."
    },
    {
      "id": "jealin-earrings-097",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-097.jpg",
      "cn": "轻奢耳钉 097",
      "en": "Luxe Earrings 097",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-098",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-098.jpg",
      "cn": "轻奢耳钉 098",
      "en": "Luxe Earrings 098",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-099",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-099.jpg",
      "cn": "轻奢耳钉 099",
      "en": "Luxe Earrings 099",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    },
    {
      "id": "jealin-earrings-100",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-100.jpg",
      "cn": "轻奢耳钉 100",
      "en": "Luxe Earrings 100",
      "metaCn": "修饰脸型 / 通勤聚会",
      "metaEn": "Face-framing / Daily and occasion wear",
      "price": 38888,
      "descCn": "适合日常、约会和派对佩戴，耳钉或垂坠设计能自然修饰脸型。",
      "descEn": "Made for daily looks, dates and events, with stud or drop details that frame the face naturally."
    }
  ]
};
