window.JEALIN_DEFAULT_CONFIG = {
  "settings": {
    "brand": "Jealin",
    "tagline": "Priceless beauty",
    "location": "Lagos, Nigeria",
    "whatsappNumber": "",
    "heroImage": "assets/jealin-hero-jewelry.png"
  },
  "categories": [
    {
      "key": "all",
      "cn": "全部",
      "en": "All"
    },
    {
      "key": "earrings",
      "cn": "耳饰",
      "en": "Earrings"
    },
    {
      "key": "necklace",
      "cn": "项链",
      "en": "Necklaces"
    },
    {
      "key": "bracelet",
      "cn": "手链",
      "en": "Bracelets"
    },
    {
      "key": "ring",
      "cn": "戒指",
      "en": "Rings"
    },
    {
      "key": "bangle",
      "cn": "手镯",
      "en": "Bangles"
    },
    {
      "key": "hair",
      "cn": "发饰",
      "en": "Hair Accessories"
    }
  ],
  "products": [
    {
      "id": "jealin-earrings-001",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-001.jpg",
      "cn": "流苏闪钻耳饰 01",
      "en": "Crystal Tassel Earrings 01",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-002",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-002.jpg",
      "cn": "花瓣珍珠耳饰 02",
      "en": "Petal Pearl Earrings 02",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-003",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-003.jpg",
      "cn": "蝴蝶垂坠耳饰 03",
      "en": "Butterfly Drop Earrings 03",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-004",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-004.jpg",
      "cn": "轻奢长款耳饰 04",
      "en": "Luxury Drop Earrings 04",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-005",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-005.jpg",
      "cn": "甜美花语耳饰 05",
      "en": "Floral Charm Earrings 05",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-006",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-006.jpg",
      "cn": "流苏闪钻耳饰 06",
      "en": "Crystal Tassel Earrings 06",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-007",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-007.jpg",
      "cn": "花瓣珍珠耳饰 07",
      "en": "Petal Pearl Earrings 07",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-008",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-008.jpg",
      "cn": "蝴蝶垂坠耳饰 08",
      "en": "Butterfly Drop Earrings 08",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-009",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-009.jpg",
      "cn": "轻奢长款耳饰 09",
      "en": "Luxury Drop Earrings 09",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-010",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-010.jpg",
      "cn": "甜美花语耳饰 10",
      "en": "Floral Charm Earrings 10",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-011",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-011.jpg",
      "cn": "流苏闪钻耳饰 11",
      "en": "Crystal Tassel Earrings 11",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-012",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-012.jpg",
      "cn": "花瓣珍珠耳饰 12",
      "en": "Petal Pearl Earrings 12",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-013",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-013.jpg",
      "cn": "蝴蝶垂坠耳饰 13",
      "en": "Butterfly Drop Earrings 13",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-014",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-014.jpg",
      "cn": "轻奢长款耳饰 14",
      "en": "Luxury Drop Earrings 14",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-015",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-015.jpg",
      "cn": "甜美花语耳饰 15",
      "en": "Floral Charm Earrings 15",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-016",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-016.jpg",
      "cn": "流苏闪钻耳饰 16",
      "en": "Crystal Tassel Earrings 16",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-017",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-017.jpg",
      "cn": "花瓣珍珠耳饰 17",
      "en": "Petal Pearl Earrings 17",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-necklace-001",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-018.jpg",
      "cn": "珍珠锁骨项链 01",
      "en": "Pearl Collarbone Necklace 01",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-002",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-019.jpg",
      "cn": "花形吊坠项链 02",
      "en": "Floral Pendant Necklace 02",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-003",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-020.jpg",
      "cn": "复古宫廷项链 03",
      "en": "Vintage Palace Necklace 03",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-004",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-021.jpg",
      "cn": "闪钻吊坠项链 04",
      "en": "Crystal Pendant Necklace 04",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-005",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-022.jpg",
      "cn": "优雅叠戴项链 05",
      "en": "Elegant Layered Necklace 05",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-006",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-023.jpg",
      "cn": "珍珠锁骨项链 06",
      "en": "Pearl Collarbone Necklace 06",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-007",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-024.jpg",
      "cn": "花形吊坠项链 07",
      "en": "Floral Pendant Necklace 07",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-008",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-025.jpg",
      "cn": "复古宫廷项链 08",
      "en": "Vintage Palace Necklace 08",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-009",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-026.jpg",
      "cn": "闪钻吊坠项链 09",
      "en": "Crystal Pendant Necklace 09",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-010",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-027.jpg",
      "cn": "优雅叠戴项链 10",
      "en": "Elegant Layered Necklace 10",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-011",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-028.jpg",
      "cn": "珍珠锁骨项链 11",
      "en": "Pearl Collarbone Necklace 11",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-012",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-029.jpg",
      "cn": "花形吊坠项链 12",
      "en": "Floral Pendant Necklace 12",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-013",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-030.jpg",
      "cn": "复古宫廷项链 13",
      "en": "Vintage Palace Necklace 13",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-014",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-031.jpg",
      "cn": "闪钻吊坠项链 14",
      "en": "Crystal Pendant Necklace 14",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-015",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-032.jpg",
      "cn": "优雅叠戴项链 15",
      "en": "Elegant Layered Necklace 15",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-016",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-033.jpg",
      "cn": "珍珠锁骨项链 16",
      "en": "Pearl Collarbone Necklace 16",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-017",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-034.jpg",
      "cn": "花形吊坠项链 17",
      "en": "Floral Pendant Necklace 17",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-earrings-018",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-035.jpg",
      "cn": "蝴蝶垂坠耳饰 18",
      "en": "Butterfly Drop Earrings 18",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-019",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-036.jpg",
      "cn": "轻奢长款耳饰 19",
      "en": "Luxury Drop Earrings 19",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-020",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-037.jpg",
      "cn": "甜美花语耳饰 20",
      "en": "Floral Charm Earrings 20",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-021",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-038.jpg",
      "cn": "流苏闪钻耳饰 21",
      "en": "Crystal Tassel Earrings 21",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-022",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-039.jpg",
      "cn": "花瓣珍珠耳饰 22",
      "en": "Petal Pearl Earrings 22",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-hair-001",
      "category": "hair",
      "shape": "earrings",
      "image": "assets/products/product-040.jpg",
      "cn": "花朵发夹饰品 01",
      "en": "Floral Hair Clip 01",
      "metaCn": "发型点缀 / 甜美造型",
      "metaEn": "Hair accent / Sweet styling",
      "price": 38888,
      "descCn": "适合半扎发、盘发和日常造型，让整体穿搭更有层次。",
      "descEn": "A sweet accent for half-up hair, updos and daily styling, adding texture to the whole look."
    },
    {
      "id": "jealin-hair-002",
      "category": "hair",
      "shape": "earrings",
      "image": "assets/products/product-041.jpg",
      "cn": "甜美造型发饰 02",
      "en": "Sweet Hair Accessory 02",
      "metaCn": "发型点缀 / 甜美造型",
      "metaEn": "Hair accent / Sweet styling",
      "price": 38888,
      "descCn": "适合半扎发、盘发和日常造型，让整体穿搭更有层次。",
      "descEn": "A sweet accent for half-up hair, updos and daily styling, adding texture to the whole look."
    },
    {
      "id": "jealin-hair-003",
      "category": "hair",
      "shape": "earrings",
      "image": "assets/products/product-042.jpg",
      "cn": "立体花瓣发饰 03",
      "en": "Layered Floral Hairpiece 03",
      "metaCn": "发型点缀 / 甜美造型",
      "metaEn": "Hair accent / Sweet styling",
      "price": 38888,
      "descCn": "适合半扎发、盘发和日常造型，让整体穿搭更有层次。",
      "descEn": "A sweet accent for half-up hair, updos and daily styling, adding texture to the whole look."
    },
    {
      "id": "jealin-hair-004",
      "category": "hair",
      "shape": "earrings",
      "image": "assets/products/product-043.jpg",
      "cn": "花朵发夹饰品 04",
      "en": "Floral Hair Clip 04",
      "metaCn": "发型点缀 / 甜美造型",
      "metaEn": "Hair accent / Sweet styling",
      "price": 38888,
      "descCn": "适合半扎发、盘发和日常造型，让整体穿搭更有层次。",
      "descEn": "A sweet accent for half-up hair, updos and daily styling, adding texture to the whole look."
    },
    {
      "id": "jealin-hair-005",
      "category": "hair",
      "shape": "earrings",
      "image": "assets/products/product-044.jpg",
      "cn": "甜美造型发饰 05",
      "en": "Sweet Hair Accessory 05",
      "metaCn": "发型点缀 / 甜美造型",
      "metaEn": "Hair accent / Sweet styling",
      "price": 38888,
      "descCn": "适合半扎发、盘发和日常造型，让整体穿搭更有层次。",
      "descEn": "A sweet accent for half-up hair, updos and daily styling, adding texture to the whole look."
    },
    {
      "id": "jealin-hair-006",
      "category": "hair",
      "shape": "earrings",
      "image": "assets/products/product-045.jpg",
      "cn": "立体花瓣发饰 06",
      "en": "Layered Floral Hairpiece 06",
      "metaCn": "发型点缀 / 甜美造型",
      "metaEn": "Hair accent / Sweet styling",
      "price": 38888,
      "descCn": "适合半扎发、盘发和日常造型，让整体穿搭更有层次。",
      "descEn": "A sweet accent for half-up hair, updos and daily styling, adding texture to the whole look."
    },
    {
      "id": "jealin-earrings-023",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-046.jpg",
      "cn": "蝴蝶垂坠耳饰 23",
      "en": "Butterfly Drop Earrings 23",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-024",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-047.jpg",
      "cn": "轻奢长款耳饰 24",
      "en": "Luxury Drop Earrings 24",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-025",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-048.jpg",
      "cn": "甜美花语耳饰 25",
      "en": "Floral Charm Earrings 25",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-026",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-049.jpg",
      "cn": "流苏闪钻耳饰 26",
      "en": "Crystal Tassel Earrings 26",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-027",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-050.jpg",
      "cn": "花瓣珍珠耳饰 27",
      "en": "Petal Pearl Earrings 27",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-028",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-051.jpg",
      "cn": "蝴蝶垂坠耳饰 28",
      "en": "Butterfly Drop Earrings 28",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-029",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-052.jpg",
      "cn": "轻奢长款耳饰 29",
      "en": "Luxury Drop Earrings 29",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-030",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-053.jpg",
      "cn": "甜美花语耳饰 30",
      "en": "Floral Charm Earrings 30",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-031",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-054.jpg",
      "cn": "流苏闪钻耳饰 31",
      "en": "Crystal Tassel Earrings 31",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-earrings-032",
      "category": "earrings",
      "shape": "earrings",
      "image": "assets/products/product-055.jpg",
      "cn": "花瓣珍珠耳饰 32",
      "en": "Petal Pearl Earrings 32",
      "metaCn": "修饰脸型 / 派对通勤",
      "metaEn": "Face-framing / Party and daily wear",
      "price": 38888,
      "descCn": "适合约会、聚会和日常穿搭，垂坠或花形设计能自然提升脸部线条。",
      "descEn": "Made for dates, events and daily outfits, with a flattering shape that adds instant polish."
    },
    {
      "id": "jealin-ring-001",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-056.jpg",
      "cn": "闪钻开口戒指 01",
      "en": "Crystal Open Ring 01",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-002",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-057.jpg",
      "cn": "花语金色戒指 02",
      "en": "Floral Gold Ring 02",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-003",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-058.jpg",
      "cn": "甜美宝石戒指 03",
      "en": "Gem Accent Ring 03",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-004",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-059.jpg",
      "cn": "轻奢造型戒指 04",
      "en": "Luxury Statement Ring 04",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-005",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-060.jpg",
      "cn": "日常精致戒指 05",
      "en": "Daily Polish Ring 05",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-006",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-061.jpg",
      "cn": "闪钻开口戒指 06",
      "en": "Crystal Open Ring 06",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-007",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-062.jpg",
      "cn": "花语金色戒指 07",
      "en": "Floral Gold Ring 07",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-008",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-063.jpg",
      "cn": "甜美宝石戒指 08",
      "en": "Gem Accent Ring 08",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-009",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-064.jpg",
      "cn": "轻奢造型戒指 09",
      "en": "Luxury Statement Ring 09",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-010",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-065.jpg",
      "cn": "日常精致戒指 10",
      "en": "Daily Polish Ring 10",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-011",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-066.jpg",
      "cn": "闪钻开口戒指 11",
      "en": "Crystal Open Ring 11",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-012",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-067.jpg",
      "cn": "花语金色戒指 12",
      "en": "Floral Gold Ring 12",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-013",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-068.jpg",
      "cn": "甜美宝石戒指 13",
      "en": "Gem Accent Ring 13",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-014",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-069.jpg",
      "cn": "轻奢造型戒指 14",
      "en": "Luxury Statement Ring 14",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-015",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-070.jpg",
      "cn": "日常精致戒指 15",
      "en": "Daily Polish Ring 15",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-016",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-071.jpg",
      "cn": "闪钻开口戒指 16",
      "en": "Crystal Open Ring 16",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-017",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-072.jpg",
      "cn": "花语金色戒指 17",
      "en": "Floral Gold Ring 17",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-018",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-073.jpg",
      "cn": "甜美宝石戒指 18",
      "en": "Gem Accent Ring 18",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-019",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-074.jpg",
      "cn": "轻奢造型戒指 19",
      "en": "Luxury Statement Ring 19",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-020",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-075.jpg",
      "cn": "日常精致戒指 20",
      "en": "Daily Polish Ring 20",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-021",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-076.jpg",
      "cn": "闪钻开口戒指 21",
      "en": "Crystal Open Ring 21",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-022",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-077.jpg",
      "cn": "花语金色戒指 22",
      "en": "Floral Gold Ring 22",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-023",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-078.jpg",
      "cn": "甜美宝石戒指 23",
      "en": "Gem Accent Ring 23",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-024",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-079.jpg",
      "cn": "轻奢造型戒指 24",
      "en": "Luxury Statement Ring 24",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-025",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-080.jpg",
      "cn": "日常精致戒指 25",
      "en": "Daily Polish Ring 25",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-026",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-081.jpg",
      "cn": "闪钻开口戒指 26",
      "en": "Crystal Open Ring 26",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-027",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-082.jpg",
      "cn": "花语金色戒指 27",
      "en": "Floral Gold Ring 27",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-028",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-083.jpg",
      "cn": "甜美宝石戒指 28",
      "en": "Gem Accent Ring 28",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-029",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-084.jpg",
      "cn": "轻奢造型戒指 29",
      "en": "Luxury Statement Ring 29",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-ring-030",
      "category": "ring",
      "shape": "ring",
      "image": "assets/products/product-085.jpg",
      "cn": "日常精致戒指 30",
      "en": "Daily Polish Ring 30",
      "metaCn": "指尖闪耀 / 日常精致",
      "metaEn": "Finger sparkle / Daily polish",
      "price": 38888,
      "descCn": "适合单戴或叠戴，细节感强，拍照和日常举手之间都更精致。",
      "descEn": "Wear alone or stacked for subtle sparkle that looks polished in photos and everyday gestures."
    },
    {
      "id": "jealin-necklace-018",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-086.jpg",
      "cn": "复古宫廷项链 18",
      "en": "Vintage Palace Necklace 18",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-019",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-087.jpg",
      "cn": "闪钻吊坠项链 19",
      "en": "Crystal Pendant Necklace 19",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-020",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-088.jpg",
      "cn": "优雅叠戴项链 20",
      "en": "Elegant Layered Necklace 20",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-021",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-089.jpg",
      "cn": "珍珠锁骨项链 21",
      "en": "Pearl Collarbone Necklace 21",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-022",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-090.jpg",
      "cn": "花形吊坠项链 22",
      "en": "Floral Pendant Necklace 22",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-023",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-091.jpg",
      "cn": "复古宫廷项链 23",
      "en": "Vintage Palace Necklace 23",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-024",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-092.jpg",
      "cn": "闪钻吊坠项链 24",
      "en": "Crystal Pendant Necklace 24",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-025",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-093.jpg",
      "cn": "优雅叠戴项链 25",
      "en": "Elegant Layered Necklace 25",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-026",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-094.jpg",
      "cn": "珍珠锁骨项链 26",
      "en": "Pearl Collarbone Necklace 26",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-027",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-095.jpg",
      "cn": "花形吊坠项链 27",
      "en": "Floral Pendant Necklace 27",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-028",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-096.jpg",
      "cn": "复古宫廷项链 28",
      "en": "Vintage Palace Necklace 28",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-029",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-097.jpg",
      "cn": "闪钻吊坠项链 29",
      "en": "Crystal Pendant Necklace 29",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-030",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-098.jpg",
      "cn": "优雅叠戴项链 30",
      "en": "Elegant Layered Necklace 30",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-031",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-099.jpg",
      "cn": "珍珠锁骨项链 31",
      "en": "Pearl Collarbone Necklace 31",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-032",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-100.jpg",
      "cn": "花形吊坠项链 32",
      "en": "Floral Pendant Necklace 32",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-033",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-101.jpg",
      "cn": "复古宫廷项链 33",
      "en": "Vintage Palace Necklace 33",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-034",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-102.jpg",
      "cn": "闪钻吊坠项链 34",
      "en": "Crystal Pendant Necklace 34",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-035",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-103.jpg",
      "cn": "优雅叠戴项链 35",
      "en": "Elegant Layered Necklace 35",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-036",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-104.jpg",
      "cn": "珍珠锁骨项链 36",
      "en": "Pearl Collarbone Necklace 36",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-necklace-037",
      "category": "necklace",
      "shape": "necklace",
      "image": "assets/products/product-105.jpg",
      "cn": "花形吊坠项链 37",
      "en": "Floral Pendant Necklace 37",
      "metaCn": "锁骨亮点 / 精致搭配",
      "metaEn": "Collarbone accent / Refined styling",
      "price": 38888,
      "descCn": "适合连衣裙、衬衫和晚宴造型，能让颈部线条更精致。",
      "descEn": "A refined accent for dresses, shirts and evening looks, designed to brighten the neckline."
    },
    {
      "id": "jealin-bracelet-001",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-106.jpg",
      "cn": "闪钻细链手链 01",
      "en": "Crystal Chain Bracelet 01",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-002",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-107.jpg",
      "cn": "绿宝石调节手链 02",
      "en": "Emerald Adjustable Bracelet 02",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-003",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-108.jpg",
      "cn": "蝴蝶金色手链 03",
      "en": "Butterfly Gold Bracelet 03",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-004",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-109.jpg",
      "cn": "轻奢叠戴手链 04",
      "en": "Luxury Layering Bracelet 04",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-005",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-110.jpg",
      "cn": "优雅通勤手链 05",
      "en": "Elegant Daily Bracelet 05",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-006",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-111.jpg",
      "cn": "闪钻细链手链 06",
      "en": "Crystal Chain Bracelet 06",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-007",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-112.jpg",
      "cn": "绿宝石调节手链 07",
      "en": "Emerald Adjustable Bracelet 07",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-008",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-113.jpg",
      "cn": "蝴蝶金色手链 08",
      "en": "Butterfly Gold Bracelet 08",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-009",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-114.jpg",
      "cn": "轻奢叠戴手链 09",
      "en": "Luxury Layering Bracelet 09",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-010",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-115.jpg",
      "cn": "优雅通勤手链 10",
      "en": "Elegant Daily Bracelet 10",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-011",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-116.jpg",
      "cn": "闪钻细链手链 11",
      "en": "Crystal Chain Bracelet 11",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-012",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-117.jpg",
      "cn": "绿宝石调节手链 12",
      "en": "Emerald Adjustable Bracelet 12",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-013",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-118.jpg",
      "cn": "蝴蝶金色手链 13",
      "en": "Butterfly Gold Bracelet 13",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-014",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-119.jpg",
      "cn": "轻奢叠戴手链 14",
      "en": "Luxury Layering Bracelet 14",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-015",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-120.jpg",
      "cn": "优雅通勤手链 15",
      "en": "Elegant Daily Bracelet 15",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-016",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-121.jpg",
      "cn": "闪钻细链手链 16",
      "en": "Crystal Chain Bracelet 16",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-017",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-122.jpg",
      "cn": "绿宝石调节手链 17",
      "en": "Emerald Adjustable Bracelet 17",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-018",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-123.jpg",
      "cn": "蝴蝶金色手链 18",
      "en": "Butterfly Gold Bracelet 18",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-019",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-124.jpg",
      "cn": "轻奢叠戴手链 19",
      "en": "Luxury Layering Bracelet 19",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-020",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-125.jpg",
      "cn": "优雅通勤手链 20",
      "en": "Elegant Daily Bracelet 20",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-021",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-126.jpg",
      "cn": "闪钻细链手链 21",
      "en": "Crystal Chain Bracelet 21",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-022",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-127.jpg",
      "cn": "绿宝石调节手链 22",
      "en": "Emerald Adjustable Bracelet 22",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-023",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-128.jpg",
      "cn": "蝴蝶金色手链 23",
      "en": "Butterfly Gold Bracelet 23",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-024",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-129.jpg",
      "cn": "轻奢叠戴手链 24",
      "en": "Luxury Layering Bracelet 24",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-025",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-130.jpg",
      "cn": "优雅通勤手链 25",
      "en": "Elegant Daily Bracelet 25",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-026",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-131.jpg",
      "cn": "闪钻细链手链 26",
      "en": "Crystal Chain Bracelet 26",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-027",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-132.jpg",
      "cn": "绿宝石调节手链 27",
      "en": "Emerald Adjustable Bracelet 27",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-028",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-133.jpg",
      "cn": "蝴蝶金色手链 28",
      "en": "Butterfly Gold Bracelet 28",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-029",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-134.jpg",
      "cn": "轻奢叠戴手链 29",
      "en": "Luxury Layering Bracelet 29",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-030",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-135.jpg",
      "cn": "优雅通勤手链 30",
      "en": "Elegant Daily Bracelet 30",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    },
    {
      "id": "jealin-bracelet-031",
      "category": "bracelet",
      "shape": "bracelet",
      "image": "assets/products/product-136.jpg",
      "cn": "闪钻细链手链 31",
      "en": "Crystal Chain Bracelet 31",
      "metaCn": "腕间亮点 / 可调节搭配",
      "metaEn": "Wrist accent / Easy styling",
      "price": 38888,
      "descCn": "适合与腕表、戒指或其他手链叠搭，给日常造型增加亮点。",
      "descEn": "Pairs easily with watches, rings or other bracelets for a polished wrist stack."
    }
  ]
};
